@startuml
:Socios:
rectangle Fábrica{
(Producto)
(Venta)<..(App) :extends
(Beneficios)
(App)
(Tienda Física) ..>(Venta) :extends
(Socios) ..>(Venta) :extends
(Tienda Socio)..>(Venta) :extends
(Comprar Producto)
(Producto)
}
(Producto) -> :Socios:
:Cliente: -(App)
:Cliente: -(Comprar Producto)
(Venta) <- (Beneficios) :include
(Comprar Producto) -> (Venta)
:Socios: ->(Beneficios)
@enduml
