@startuml
:Alumno:
:Profesor:
rectangle Moodle{
(Creacion curso)
(Grupos)
(Gestión temas)<.down. (Contenidos) :extend
(Gestión temas) <.down.(Tareas) :extend
(Gestión calificaciones)
:Profesor: ->(Creacion curso)
:Profesor: -down->(Gestión temas)
:Profesor: -down-> (Grupos)
:Profesor: ->(Gestión calificaciones)
(Grupos) <.down. (Alumnos) :extend
(Grupos) <.down. (Matriculación) :extend
:Alumno: -up-> (Acciones realizadas)
(Acciones realizadas) <.up. (Contenidos)
(Acciones realizadas) <.up. (Tareas)
:Profesor: -> (Acciones realizadas)
}
@enduml
